[package]
name = "typy-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
clap = {version = "4.5.30", features = ["derive"]}
rand = "0.9"
tui = "0.19.0"
dirs = "6.0"
toml = "0.8.20"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.5.0"
chrono = { version = "0.4", features = ["serde"] }
comfy-table = "7.1.4"
derive_more = {version = "1.0.0-beta", features = ["from"]}
